/**
 * Single source of truth for business details, shipping/tax rules and the catalogue.
 * All money is stored in cents as integers to avoid floating-point rounding errors.
 * Listed prices exclude sales tax, which is estimated at checkout from the shipping
 * address, per standard US practice.
 */

export const BUSINESS = {
  name: 'Fernway',
  legalName: 'Fernway LLC',
  tagline: 'Home & Garden, chosen well',
  stateOfFormation: 'Oregon',
  email: 'hello@shopfernway.us',
  supportEmail: 'support@shopfernway.us',
  phone: '1 (800) 555-0142',
  phoneHref: 'tel:+18005550142',
  address: {
    line1: '1420 SE Cedar Mill Road, Suite 5',
    line2: '',
    city: 'Portland',
    state: 'OR',
    zip: '97214',
    country: 'United States'
  },
  hours: [
    { days: 'Monday to Friday', time: '9:00am – 5:30pm PT' },
    { days: 'Saturday', time: '10:00am – 2:00pm PT' },
    { days: 'Sunday & federal holidays', time: 'Closed' }
  ],
  established: 2016
};

/** Shipping bands and the estimated sales-tax rate. Shown in full before checkout. */
export const DELIVERY = {
  standard: { label: 'Standard shipping', days: '3–5 business days', price: 595 },
  express: { label: 'Express shipping', days: '1–2 business days', price: 1495 },
  freeThreshold: 7500,
  bulkySurcharge: 2500,
  salesTaxRate: 0.0725
};

/**
 * Discount codes. Percentage discounts apply to the merchandise subtotal;
 * sales tax and any free-shipping threshold are then assessed on the discounted
 * amount. Codes are matched case-insensitively.
 */
export const COUPONS = {
  NEWUSER: {
    code: 'NEWUSER',
    type: 'percent',
    value: 50,
    label: '50% off your first order',
    shortLabel: 'NEWUSER · 50% off'
  }
};

export function findCoupon(code) {
  if (!code) return null;
  return COUPONS[String(code).trim().toUpperCase()] || null;
}

export const CATEGORIES = [
  {
    id: 'outdoor-furniture',
    name: 'Outdoor Furniture',
    blurb: 'Seating and tables built to stay outside all year.',
    image: 'assets/images/cat-outdoor-furniture.jpg',
    alt: 'Modern outdoor seating area with pale cushions on a stone terrace'
  },
  {
    id: 'planters',
    name: 'Planters & Pots',
    blurb: 'Frost-resistant ceramic, terracotta and hanging planters.',
    image: 'assets/images/cat-planters.jpg',
    alt: 'A row of red and pink flowering plants in terracotta pots on a ledge'
  },
  {
    id: 'indoor-greenery',
    name: 'Indoor Greenery',
    blurb: 'Nursery-grown houseplants, potted and ready to place.',
    image: 'assets/images/cat-indoor-plants.jpg',
    alt: 'A large green leafy houseplant beside a bright window'
  },
  {
    id: 'tools',
    name: 'Garden Tools',
    blurb: 'Forged steel and hardwood tools that outlast the season.',
    image: 'assets/images/cat-tools.jpg',
    alt: 'A green garden scoop filled with potting soil next to a pair of snips'
  },
  {
    id: 'lighting',
    name: 'Outdoor Lighting',
    blurb: 'Solar lanterns and string lighting for long evenings.',
    image: 'assets/images/cat-lighting.jpg',
    alt: 'A garden lantern glowing on a post among planting at dusk'
  },
  {
    id: 'decor',
    name: 'Decor & Textiles',
    blurb: 'Rugs, cushions, statues and finishing touches.',
    image: 'assets/images/cat-decor.jpg',
    alt: 'An empty wooden chair and side table in dappled garden sunlight'
  }
];

export const PRODUCTS = [
  {
    id: 'ridgeline-7-piece-dining-set',
    name: 'Ridgeline 7-Piece Dining Set',
    category: 'outdoor-furniture',
    price: 149900,
    image: 'assets/images/pool/outdoor-furniture-00.jpg',
    alt: 'A seven-piece powder-coated dining set that seats six, built for full seasons outdoors.',
    summary: 'A seven-piece powder-coated dining set that seats six, built for full seasons outdoors.',
    description: 'An aluminum-framed dining set with a slatted table and six sling chairs. The frame is powder-coated so it will not rust, and the sling seats dry fast after rain and shrug off UV fading.',
    specs: [['Seats', '6'], ['Frame', 'Powder-coated aluminum'], ['Table', '63 in × 35 in'], ['Care', 'Wipe clean; cover over winter'], ['Warranty', '3 years frame']],
    stock: 'in-stock',
    bulky: true,
    featured: true
  },
  {
    id: 'brookside-5-piece-patio-set',
    name: 'Brookside 5-Piece Patio Set',
    category: 'outdoor-furniture',
    price: 89900,
    image: 'assets/images/pool/outdoor-furniture-01.jpg',
    alt: 'A compact five-piece steel patio set for smaller decks and balconies.',
    summary: 'A compact five-piece steel patio set for smaller decks and balconies.',
    description: 'Four stackable sling chairs and a round mesh-top table in weatherproof steel. The chairs stack for storage, and the mesh top lets rain run straight through instead of pooling.',
    specs: [['Seats', '4'], ['Frame', 'Powder-coated steel'], ['Table', 'Ø 42 in'], ['Care', 'Touch up chips to prevent rust'], ['Warranty', '2 years']],
    stock: 'in-stock',
    bulky: true,
    featured: false
  },
  {
    id: 'sonoma-lounge-chair',
    name: 'Sonoma Lounge Chair',
    category: 'outdoor-furniture',
    price: 38900,
    image: 'assets/images/pool/outdoor-furniture-02.jpg',
    alt: 'A deep, low lounge chair with a woven pouf, made for slow afternoons.',
    summary: 'A deep, low lounge chair with a woven pouf, made for slow afternoons.',
    description: 'A boucle-cushioned lounge chair over a solid hardwood frame, paired with a woven rope pouf. The quick-dry foam cushion is wrapped in a solution-dyed fabric that resists fading and mildew.',
    specs: [['Material', 'FSC hardwood, quick-dry foam'], ['Dimensions', 'W 30 in × D 34 in × H 28 in'], ['Cushion', 'Removable, washable cover'], ['Care', 'Store cushions dry over winter'], ['Warranty', '3 years frame']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'harbor-wicker-lounge-set',
    name: 'Harbor Wicker Lounge Set',
    category: 'outdoor-furniture',
    price: 124900,
    image: 'assets/images/pool/outdoor-furniture-03.jpg',
    alt: 'A four-piece all-weather wicker lounge set with plush water-resistant cushions.',
    summary: 'A four-piece all-weather wicker lounge set with plush water-resistant cushions.',
    description: 'Hand-woven PE wicker over rustproof aluminum, with two chairs, a loveseat and a coffee table. The wicker holds up to sun and rain that would crack cheaper resin.',
    specs: [['Pieces', '2 chairs, loveseat, table'], ['Frame', 'Aluminum, PE wicker'], ['Cushions', 'Quick-dry, washable covers'], ['Care', 'Hose clean; cover cushions'], ['Warranty', '3 years frame']],
    stock: 'in-stock',
    bulky: true,
    featured: false
  },
  {
    id: 'teakwood-lounge-set',
    name: 'Teakwood Lounge Set',
    category: 'outdoor-furniture',
    price: 139900,
    image: 'assets/images/pool/outdoor-furniture-04.jpg',
    alt: 'A three-seat teak lounge grouping that weathers to a soft silver-gray.',
    summary: 'A three-seat teak lounge grouping that weathers to a soft silver-gray.',
    description: 'Solid teak framing with thick off-white cushions. Left untreated the teak silvers gracefully; oiled twice a year it keeps its honey tone.',
    specs: [['Material', 'Solid teak, stainless fixings'], ['Pieces', '2 chairs, ottoman, table'], ['Cushions', 'Included, washable covers'], ['Care', 'Oil twice yearly to keep color'], ['Warranty', '5 years frame']],
    stock: 'in-stock',
    bulky: true,
    featured: true
  },
  {
    id: 'vero-counter-stool-set',
    name: 'Vero Counter Stool Set',
    category: 'outdoor-furniture',
    price: 59900,
    image: 'assets/images/pool/outdoor-furniture-05.jpg',
    alt: 'A set of four woven counter-height stools for outdoor bars and high tables.',
    summary: 'A set of four woven counter-height stools for outdoor bars and high tables.',
    description: 'Counter-height stools with woven rope seats over powder-coated steel, with footrests sized for a standard bar table. Stable on decking and easy to wipe down.',
    specs: [['Seats', '4 stools'], ['Seat height', '26 in'], ['Frame', 'Powder-coated steel, rope weave'], ['Care', 'Wipe clean'], ['Warranty', '2 years']],
    stock: 'in-stock',
    bulky: true,
    featured: false
  },
  {
    id: 'teak-club-chair-ottoman',
    name: 'Teak Club Chair & Ottoman',
    category: 'outdoor-furniture',
    price: 44900,
    image: 'assets/images/pool/outdoor-furniture-06.jpg',
    alt: 'A wide teak club chair with a matching ottoman and deep cushions.',
    summary: 'A wide teak club chair with a matching ottoman and deep cushions.',
    description: 'A generously proportioned teak club chair with a pull-up ottoman, sized for putting your feet up with a book. Cushions are quick-dry and slipcovered.',
    specs: [['Material', 'Solid teak'], ['Dimensions', 'W 32 in × D 34 in × H 30 in'], ['Includes', 'Chair and ottoman'], ['Care', 'Oil to retain color'], ['Warranty', '5 years frame']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'bistro-wire-chair-pair',
    name: 'Bistro Wire Chair Pair',
    category: 'outdoor-furniture',
    price: 24900,
    image: 'assets/images/pool/outdoor-furniture-07.jpg',
    alt: 'Two sculptural powder-coated wire chairs for a modern patio corner.',
    summary: 'Two sculptural powder-coated wire chairs for a modern patio corner.',
    description: 'A pair of open wire-frame chairs that read as sculpture and shed rain instantly. Light enough to move, sturdy enough to leave out.',
    specs: [['Seats', '2 chairs'], ['Frame', 'Powder-coated steel wire'], ['Seat height', '18 in'], ['Care', 'Wipe clean; touch up chips'], ['Warranty', '2 years']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'cloud-deep-seat-armchair',
    name: 'Cloud Deep-Seat Armchair',
    category: 'outdoor-furniture',
    price: 42900,
    image: 'assets/images/pool/outdoor-furniture-08.jpg',
    alt: 'An oversized deep-seat armchair with a cloud-soft, quick-dry cushion.',
    summary: 'An oversized deep-seat armchair with a cloud-soft, quick-dry cushion.',
    description: 'A wide-armed lounge chair with an especially deep seat and a plush quick-dry cushion. The kind of chair people fight over.',
    specs: [['Material', 'Aluminum frame, quick-dry foam'], ['Dimensions', 'W 34 in × D 36 in × H 30 in'], ['Cushion', 'Washable cover'], ['Care', 'Store cushion dry'], ['Warranty', '3 years frame']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'deckhouse-sofa',
    name: 'Deckhouse Sofa',
    category: 'outdoor-furniture',
    price: 99900,
    image: 'assets/images/pool/outdoor-furniture-09.jpg',
    alt: 'A clean-lined three-seat sofa in gray all-weather upholstery.',
    summary: 'A clean-lined three-seat sofa in gray all-weather upholstery.',
    description: 'A low three-seat sofa with a powder-coated frame and gray solution-dyed cushions that resist fading. Comfortable enough for indoors, tough enough for the deck.',
    specs: [['Seats', '3'], ['Frame', 'Powder-coated aluminum'], ['Dimensions', 'W 78 in × D 33 in × H 29 in'], ['Care', 'Cover over winter'], ['Warranty', '3 years frame']],
    stock: 'in-stock',
    bulky: true,
    featured: false
  },
  {
    id: 'crescent-modular-sectional',
    name: 'Crescent Modular Sectional',
    category: 'outdoor-furniture',
    price: 189900,
    image: 'assets/images/pool/outdoor-furniture-10.jpg',
    alt: 'A curved modular sectional that wraps a fire pit or a view.',
    summary: 'A curved modular sectional that wraps a fire pit or a view.',
    description: 'Six low modular pieces that arrange into a gentle arc around a table or fire feature. Rearrange them as your space changes; the covers unzip for washing.',
    specs: [['Pieces', '6 modules'], ['Frame', 'Aluminum, PE weave'], ['Cushions', 'Quick-dry, washable'], ['Care', 'Hose clean; store cushions'], ['Warranty', '3 years frame']],
    stock: 'low-stock',
    bulky: true,
    featured: true
  },
  {
    id: 'linen-accent-armchair',
    name: 'Linen Accent Armchair',
    category: 'outdoor-furniture',
    price: 34900,
    image: 'assets/images/pool/outdoor-furniture-11.jpg',
    alt: 'A softly tailored accent armchair for a sunroom, porch or reading nook.',
    summary: 'A softly tailored accent armchair for a sunroom, porch or reading nook.',
    description: 'An upholstered accent chair in a washed linen-look weave, at home in a bright sunroom or covered porch. Best kept out of direct rain.',
    specs: [['Material', 'Hardwood frame, linen-weave'], ['Dimensions', 'W 29 in × D 32 in × H 31 in'], ['Placement', 'Covered spaces'], ['Care', 'Spot clean'], ['Warranty', '2 years']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'brickyard-corner-sectional',
    name: 'Brickyard Corner Sectional',
    category: 'outdoor-furniture',
    price: 159900,
    image: 'assets/images/pool/outdoor-furniture-12.jpg',
    alt: 'A five-seat corner sectional with charcoal cushions and a slatted table.',
    summary: 'A five-seat corner sectional with charcoal cushions and a slatted table.',
    description: 'An L-shaped corner sectional with deep charcoal cushions and a low wooden table. Configurable left- or right-handed to fit a courtyard corner.',
    specs: [['Seats', '5'], ['Frame', 'Aluminum, PE weave'], ['Config', 'Left or right handed'], ['Care', 'Cover cushions over winter'], ['Warranty', '3 years frame']],
    stock: 'in-stock',
    bulky: true,
    featured: false
  },
  {
    id: 'rosewood-folding-armchair',
    name: 'Rosewood Folding Armchair',
    category: 'outdoor-furniture',
    price: 18900,
    image: 'assets/images/pool/outdoor-furniture-13.jpg',
    alt: 'A folding hardwood armchair with a striped cushion, ready for guests.',
    summary: 'A folding hardwood armchair with a striped cushion, ready for guests.',
    description: 'A classic folding deck armchair in oiled hardwood with a tie-on striped cushion. Folds flat to store a stack of spares for visitors.',
    specs: [['Material', 'Oiled hardwood'], ['Folded depth', '4 in'], ['Cushion', 'Tie-on, included'], ['Care', 'Oil yearly'], ['Warranty', '2 years']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'meridian-sofa-set',
    name: 'Meridian Sofa Set',
    category: 'outdoor-furniture',
    price: 169900,
    image: 'assets/images/pool/outdoor-furniture-14.jpg',
    alt: 'A three-piece gray sofa set — sofa, two chairs and a coffee table.',
    summary: 'A three-piece gray sofa set — sofa, two chairs and a coffee table.',
    description: 'A coordinated gray lounge set with a three-seat sofa, two armchairs and a slatted coffee table on rope-detailed hardwood frames. A whole living room for the deck in one order.',
    specs: [['Pieces', 'Sofa, 2 chairs, table'], ['Frame', 'Hardwood, rope detail'], ['Cushions', 'Quick-dry, washable'], ['Care', 'Store cushions dry'], ['Warranty', '3 years frame']],
    stock: 'in-stock',
    bulky: true,
    featured: true
  },
  {
    id: 'portico-caf-chair-set',
    name: 'Portico Café Chair Set',
    category: 'outdoor-furniture',
    price: 21900,
    image: 'assets/images/pool/outdoor-furniture-15.jpg',
    alt: 'Four white powder-coated café chairs for a bright breakfast corner.',
    summary: 'Four white powder-coated café chairs for a bright breakfast corner.',
    description: 'A set of four crisp white café chairs in powder-coated steel, stackable and easy to wipe. Pair with any small table for a morning-coffee spot.',
    specs: [['Seats', '4 chairs'], ['Frame', 'Powder-coated steel'], ['Feature', 'Stackable'], ['Care', 'Wipe clean'], ['Warranty', '2 years']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'wingback-patio-armchair',
    name: 'Wingback Patio Armchair',
    category: 'outdoor-furniture',
    price: 27900,
    image: 'assets/images/pool/outdoor-furniture-16.jpg',
    alt: 'A weatherproof wingback armchair that brings a little formality outside.',
    summary: 'A weatherproof wingback armchair that brings a little formality outside.',
    description: 'A high-backed wingback chair in all-weather upholstery over a hardwood frame — a considered spot by the door or under a porch. Keep the cushion covered in heavy rain.',
    specs: [['Material', 'Hardwood, all-weather fabric'], ['Dimensions', 'W 31 in × D 33 in × H 42 in'], ['Care', 'Cover in heavy rain'], ['Warranty', '2 years']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'cove-rope-lounge-chair',
    name: 'Cove Rope Lounge Chair',
    category: 'outdoor-furniture',
    price: 32900,
    image: 'assets/images/pool/outdoor-furniture-17.jpg',
    alt: 'A woven olive-rope lounge chair with a single deep seat cushion.',
    summary: 'A woven olive-rope lounge chair with a single deep seat cushion.',
    description: 'A hand-wrapped rope lounge chair in a muted olive over a rustproof frame, with one deep quick-dry cushion. Comfortable, low and modern.',
    specs: [['Material', 'Aluminum, olive rope weave'], ['Dimensions', 'W 30 in × D 33 in × H 27 in'], ['Cushion', 'Quick-dry, washable'], ['Care', 'Hose clean'], ['Warranty', '3 years frame']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'sundial-bistro-set',
    name: 'Sundial Bistro Set',
    category: 'outdoor-furniture',
    price: 15900,
    image: 'assets/images/pool/outdoor-furniture-18.jpg',
    alt: 'A cheerful three-piece bistro set for two — two chairs and a small table.',
    summary: 'A cheerful three-piece bistro set for two — two chairs and a small table.',
    description: 'A molded resin bistro set in a warm red, sized for a balcony or a sunny corner. Weatherproof, wipe-clean and light enough to move to follow the sun.',
    specs: [['Seats', '2 chairs, 1 table'], ['Material', 'UV-stable resin'], ['Table', 'Ø 24 in'], ['Care', 'Wipe clean'], ['Warranty', '2 years']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'slate-outdoor-sofa',
    name: 'Slate Outdoor Sofa',
    category: 'outdoor-furniture',
    price: 109900,
    image: 'assets/images/pool/outdoor-furniture-19.jpg',
    alt: 'A minimalist three-seat sofa in slate-gray on a fine hardwood frame.',
    summary: 'A minimalist three-seat sofa in slate-gray on a fine hardwood frame.',
    description: 'A pared-back three-seat sofa with a slim hardwood frame and slate-gray quick-dry cushions. Understated and comfortable for a modern patio.',
    specs: [['Seats', '3'], ['Frame', 'Hardwood'], ['Dimensions', 'W 80 in × D 32 in × H 28 in'], ['Care', 'Store cushions dry'], ['Warranty', '3 years frame']],
    stock: 'in-stock',
    bulky: true,
    featured: false
  },
  {
    id: 'folding-deck-chair',
    name: 'Folding Deck Chair',
    category: 'outdoor-furniture',
    price: 12900,
    image: 'assets/images/pool/decor-09.jpg',
    alt: 'A reclining hardwood folding chair with a striped tie-on cushion.',
    summary: 'A reclining hardwood folding chair with a striped tie-on cushion.',
    description: 'A multi-position folding deck chair in oiled hardwood with a comfortable striped cushion. Reclines for sunbathing and folds flat to hang in the shed.',
    specs: [['Material', 'Oiled hardwood'], ['Positions', '5-position recline'], ['Cushion', 'Tie-on, included'], ['Care', 'Oil yearly'], ['Warranty', '2 years']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'glass-top-patio-table',
    name: 'Glass-Top Patio Table',
    category: 'outdoor-furniture',
    price: 27900,
    image: 'assets/images/pool/decor-11.jpg',
    alt: 'A tempered glass-top patio table on a cast frame, seating four.',
    summary: 'A tempered glass-top patio table on a cast frame, seating four.',
    description: 'A round tempered-glass table on a powder-coated cast frame, with a center umbrella hole. Easy to wipe and steady on uneven paving.',
    specs: [['Seats', '4'], ['Top', 'Tempered glass'], ['Feature', 'Umbrella hole'], ['Care', 'Wipe clean'], ['Warranty', '2 years']],
    stock: 'in-stock',
    bulky: true,
    featured: false
  },
  {
    id: 'pallet-lounge-sofa',
    name: 'Pallet Lounge Sofa',
    category: 'outdoor-furniture',
    price: 74900,
    image: 'assets/images/pool/decor-12.jpg',
    alt: 'A chunky pallet-style lounge sofa with deep neutral cushions.',
    summary: 'A chunky pallet-style lounge sofa with deep neutral cushions.',
    description: 'A solid, low pallet-style sofa in treated pine with thick neutral cushions — relaxed and rustic for a covered patio. Keep cushions under cover between uses.',
    specs: [['Seats', '3'], ['Material', 'Treated pine'], ['Cushions', 'Included, washable covers'], ['Care', 'Cover cushions when not in use'], ['Warranty', '2 years frame']],
    stock: 'low-stock',
    bulky: true,
    featured: false
  },
  {
    id: 'trellis-stoneware-planter',
    name: 'Trellis Stoneware Planter',
    category: 'planters',
    price: 6400,
    image: 'assets/images/pool/planters-00.jpg',
    alt: 'A frost-proof stoneware planter with an embossed trellis pattern and drainage.',
    summary: 'A frost-proof stoneware planter with an embossed trellis pattern and drainage.',
    description: 'Thrown in stoneware and fired frost-proof, with a raised trellis motif and a drilled base. Works as an indoor cachepot with the plug in, or outdoors with free drainage.',
    specs: [['Material', 'Glazed stoneware'], ['Size', 'Ø 11 in × H 10 in'], ['Drainage', 'Drilled, plug included'], ['Frost', 'Frost-proof to 5°F']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'mint-glazed-pot',
    name: 'Mint Glazed Pot',
    category: 'planters',
    price: 3200,
    image: 'assets/images/pool/planters-01.jpg',
    alt: 'A rounded ceramic pot in a soft mint glaze, sized for a favorite succulent.',
    summary: 'A rounded ceramic pot in a soft mint glaze, sized for a favorite succulent.',
    description: 'A tactile rounded pot in a calm mint glaze, just right for an aloe or small succulent on a windowsill. Comes with a matching saucer.',
    specs: [['Material', 'Glazed ceramic'], ['Size', 'Ø 5 in × H 5 in'], ['Drainage', 'Hole with saucer'], ['Use', 'Indoor']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'duo-planter-set',
    name: 'Duo Planter Set',
    category: 'planters',
    price: 4800,
    image: 'assets/images/pool/planters-02.jpg',
    alt: 'A pair of tapered ceramic planters in blush and white, for a styled shelf.',
    summary: 'A pair of tapered ceramic planters in blush and white, for a styled shelf.',
    description: 'Two coordinating tapered pots — one blush, one white — that look considered grouped on a shelf or table. Each has a drainage hole and cork foot.',
    specs: [['Material', 'Glazed ceramic'], ['Sizes', 'Ø 6 in and Ø 5 in'], ['Drainage', 'Holes, cork feet'], ['Use', 'Indoor']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'tapered-cream-planter',
    name: 'Tapered Cream Planter',
    category: 'planters',
    price: 3600,
    image: 'assets/images/pool/planters-03.jpg',
    alt: 'A tall tapered planter in a matte cream glaze for upright plants.',
    summary: 'A tall tapered planter in a matte cream glaze for upright plants.',
    description: 'A slim, tall pot in a matte cream finish that flatters upright plants like a ZZ or snake plant. Drilled base with a removable plug.',
    specs: [['Material', 'Glazed ceramic'], ['Size', 'Ø 7 in × H 9 in'], ['Drainage', 'Drilled, plug included'], ['Use', 'Indoor or covered']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'polka-dot-ceramic-planter',
    name: 'Polka-Dot Ceramic Planter',
    category: 'planters',
    price: 3400,
    image: 'assets/images/pool/planters-04.jpg',
    alt: 'A playful white planter with hand-painted charcoal dots.',
    summary: 'A playful white planter with hand-painted charcoal dots.',
    description: 'A cheerful hand-decorated pot with charcoal polka dots, sized to sit on a plant stand with a trailing plant. Saucer included.',
    specs: [['Material', 'Glazed ceramic'], ['Size', 'Ø 7 in × H 6 in'], ['Drainage', 'Hole with saucer'], ['Use', 'Indoor']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'carved-stoneware-planter',
    name: 'Carved Stoneware Planter',
    category: 'planters',
    price: 5200,
    image: 'assets/images/pool/planters-05.jpg',
    alt: 'A gray stoneware planter with a carved swirl relief, frost-proof for outdoors.',
    summary: 'A gray stoneware planter with a carved swirl relief, frost-proof for outdoors.',
    description: 'A weighty stoneware planter with a carved swirling texture and a frost-proof body, so it can stay out through winter. Drilled for drainage.',
    specs: [['Material', 'Glazed stoneware'], ['Size', 'Ø 9 in × H 9 in'], ['Drainage', 'Drilled'], ['Frost', 'Frost-proof to 5°F']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'moroccan-tile-planter',
    name: 'Moroccan Tile Planter',
    category: 'planters',
    price: 4200,
    image: 'assets/images/pool/planters-06.jpg',
    alt: 'A deep-blue planter with a Moroccan tile pattern for a pop of color.',
    summary: 'A deep-blue planter with a Moroccan tile pattern for a pop of color.',
    description: 'A patterned ceramic planter in cobalt and white, inspired by Moroccan tile — a strong base for a leafy aglaonema or pothos. Indoor cachepot with saucer.',
    specs: [['Material', 'Glazed ceramic'], ['Size', 'Ø 7 in × H 7 in'], ['Drainage', 'Hole with saucer'], ['Use', 'Indoor']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'cylinder-ceramic-planter',
    name: 'Cylinder Ceramic Planter',
    category: 'planters',
    price: 3800,
    image: 'assets/images/pool/planters-07.jpg',
    alt: 'A clean white cylinder planter that suits almost any room.',
    summary: 'A clean white cylinder planter that suits almost any room.',
    description: 'A simple straight-sided cylinder in a soft white glaze — the quiet planter that lets the plant do the talking. Drilled with a plug.',
    specs: [['Material', 'Glazed ceramic'], ['Size', 'Ø 6 in × H 6 in'], ['Drainage', 'Drilled, plug included'], ['Use', 'Indoor or covered']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'delft-blue-planter',
    name: 'Delft Blue Planter',
    category: 'planters',
    price: 3900,
    image: 'assets/images/pool/planters-08.jpg',
    alt: 'A small planter in a blue-and-white patterned glaze on a matching saucer.',
    summary: 'A small planter in a blue-and-white patterned glaze on a matching saucer.',
    description: 'A patterned blue-and-white pot with an attached saucer, sized for a herb or a small palm on a table. Charming on a kitchen sill.',
    specs: [['Material', 'Glazed ceramic'], ['Size', 'Ø 5 in × H 5 in'], ['Drainage', 'Hole, attached saucer'], ['Use', 'Indoor']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'ribbed-planter-set-of-3',
    name: 'Ribbed Planter, Set of 3',
    category: 'planters',
    price: 5400,
    image: 'assets/images/pool/planters-09.jpg',
    alt: 'Three graduated ribbed planters in a soft sage, for a considered grouping.',
    summary: 'Three graduated ribbed planters in a soft sage, for a considered grouping.',
    description: 'A trio of fluted, ribbed pots in a muted sage that step up in size for an easy styled cluster. Each has a drainage hole and cork foot.',
    specs: [['Material', 'Glazed ceramic'], ['Sizes', 'Ø 4, 5 and 6 in'], ['Drainage', 'Holes, cork feet'], ['Use', 'Indoor']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'cottage-floral-planter',
    name: 'Cottage Floral Planter',
    category: 'planters',
    price: 4400,
    image: 'assets/images/pool/planters-10.jpg',
    alt: 'A square planter with a hand-painted cottage-garden floral, frost-tolerant.',
    summary: 'A square planter with a hand-painted cottage-garden floral, frost-tolerant.',
    description: 'A square pot decorated with a loose cottage-garden floral, sturdy enough for a doorstep display of bulbs. Bring under cover in a hard freeze.',
    specs: [['Material', 'Glazed earthenware'], ['Size', '7 in square × H 7 in'], ['Drainage', 'Drilled'], ['Frost', 'Shelter below freezing']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'coastal-textured-pot',
    name: 'Coastal Textured Pot',
    category: 'planters',
    price: 4000,
    image: 'assets/images/pool/planters-11.jpg',
    alt: 'A lavender-gray planter with a sandy, coastal texture.',
    summary: 'A lavender-gray planter with a sandy, coastal texture.',
    description: 'A softly textured pot in a lavender-gray that reads coastal and calm, sized for lavender or a small grass. Drilled base.',
    specs: [['Material', 'Glazed stoneware'], ['Size', 'Ø 7 in × H 7 in'], ['Drainage', 'Drilled'], ['Frost', 'Frost-resistant']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'modern-tapered-planter',
    name: 'Modern Tapered Planter',
    category: 'planters',
    price: 3600,
    image: 'assets/images/pool/planters-12.jpg',
    alt: 'A crisp white tapered planter with a drip tray for indoor greenery.',
    summary: 'A crisp white tapered planter with a drip tray for indoor greenery.',
    description: 'A modern tapered pot in bright white with a fitted drip tray, ideal for an aloe or small houseplant. Clean lines that suit any interior.',
    specs: [['Material', 'Glazed ceramic'], ['Size', 'Ø 6 in × H 6 in'], ['Drainage', 'Hole with drip tray'], ['Use', 'Indoor']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'happy-face-mini-pot',
    name: 'Happy Face Mini Pot',
    category: 'planters',
    price: 1800,
    image: 'assets/images/pool/planters-13.jpg',
    alt: 'A tiny smiling planter for a single succulent — an easy desk gift.',
    summary: 'A tiny smiling planter for a single succulent — an easy desk gift.',
    description: 'A little hand-glazed pot with a cheerful painted face, sized for one small succulent. The kind of thing that makes a desk friendlier.',
    specs: [['Material', 'Glazed ceramic'], ['Size', 'Ø 3 in × H 3 in'], ['Drainage', 'No hole; use a liner'], ['Use', 'Indoor']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'terracotta-pot-set-of-6',
    name: 'Terracotta Pot Set of 6',
    category: 'planters',
    price: 3800,
    image: 'assets/images/pool/planters-14.jpg',
    alt: 'Six classic terracotta pots, hand-thrown and ready to plant.',
    summary: 'Six classic terracotta pots, hand-thrown and ready to plant.',
    description: 'A stack of six unglazed terracotta pots that breathe — ideal for herbs, seedlings and anything that resents wet feet. Hand-thrown, so each varies slightly.',
    specs: [['Material', 'Unglazed terracotta'], ['Size', 'Ø 4 in each'], ['Drainage', 'Single hole each'], ['Note', 'Hand-thrown; slight variation']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'tuscan-terracotta-urn',
    name: 'Tuscan Terracotta Urn',
    category: 'planters',
    price: 8900,
    image: 'assets/images/pool/planters-15.jpg',
    alt: 'A large hand-thrown terracotta urn for a statement planting.',
    summary: 'A large hand-thrown terracotta urn for a statement planting.',
    description: 'A generous bellied urn in aged terracotta that anchors a doorway or path with an olive or bay. Heavy and characterful; shelter from hard freezes.',
    specs: [['Material', 'Unglazed terracotta'], ['Size', 'Ø 16 in × H 18 in'], ['Drainage', 'Drilled'], ['Frost', 'Shelter below freezing']],
    stock: 'low-stock',
    bulky: true,
    featured: true
  },
  {
    id: 'tulip-bulb-planter',
    name: 'Tulip Bulb Planter',
    category: 'planters',
    price: 4600,
    image: 'assets/images/pool/planters-16.jpg',
    alt: 'A tall white planter sized and drained for spring bulb displays.',
    summary: 'A tall white planter sized and drained for spring bulb displays.',
    description: 'A tall, footed white planter with generous depth for layering spring bulbs. Lift it onto a step for a welcoming seasonal display.',
    specs: [['Material', 'Glazed ceramic'], ['Size', 'Ø 8 in × H 12 in'], ['Drainage', 'Drilled'], ['Frost', 'Frost-resistant']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'classic-terracotta-pots-set-of-3',
    name: 'Classic Terracotta Pots, Set of 3',
    category: 'planters',
    price: 3400,
    image: 'assets/images/pool/planters-17.jpg',
    alt: 'Three graduated terracotta pots for the greenhouse bench or windowsill.',
    summary: 'Three graduated terracotta pots for the greenhouse bench or windowsill.',
    description: 'A graduated trio of honest terracotta pots that nest for storage — the workhorse of any potting bench. Unglazed, so roots breathe.',
    specs: [['Material', 'Unglazed terracotta'], ['Sizes', 'Ø 5, 6 and 7 in'], ['Drainage', 'Single hole each'], ['Note', 'Nests for storage']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'spring-bulb-pot',
    name: 'Spring Bulb Pot',
    category: 'planters',
    price: 3600,
    image: 'assets/images/pool/planters-18.jpg',
    alt: 'A single terracotta pot planted up for an instant hit of spring color.',
    summary: 'A single terracotta pot planted up for an instant hit of spring color.',
    description: 'A classic terracotta pot with the depth bulbs like, ready for tulips or daffodils. Group several on a step for a generous show.',
    specs: [['Material', 'Unglazed terracotta'], ['Size', 'Ø 8 in × H 7 in'], ['Drainage', 'Single hole'], ['Frost', 'Shelter below freezing']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'nursery-pot-bundle',
    name: 'Nursery Pot Bundle',
    category: 'planters',
    price: 2400,
    image: 'assets/images/pool/planters-19.jpg',
    alt: 'A value bundle of small nursery pots for propagating and potting on.',
    summary: 'A value bundle of small nursery pots for propagating and potting on.',
    description: 'A practical bundle of reusable nursery pots in mixed sizes for seedlings, cuttings and potting on. The unglamorous workhorse every gardener runs out of.',
    specs: [['Material', 'Recyclable plastic'], ['Contents', '12 mixed pots'], ['Drainage', 'Multiple holes'], ['Use', 'Propagation, potting on']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'monstera-deliciosa-large',
    name: 'Monstera Deliciosa, Large',
    category: 'indoor-greenery',
    price: 12000,
    image: 'assets/images/pool/indoor-greenery-00.jpg',
    alt: 'A floor-standing Swiss cheese plant on a moss pole, around 4 ft tall.',
    summary: 'A floor-standing Swiss cheese plant on a moss pole, around 4 ft tall.',
    description: 'A mature monstera trained up a moss pole, already showing the deep splits the plant is loved for. An instant statement in a bright corner.',
    specs: [['Height', 'Approx. 48 in incl. pot'], ['Pot', '10 in grow pot'], ['Light', 'Bright, indirect'], ['Water', 'When top 2 in dry'], ['Pet safe', 'No — toxic if eaten']],
    stock: 'in-stock',
    bulky: true,
    featured: true
  },
  {
    id: 'monstera-deliciosa',
    name: 'Monstera Deliciosa',
    category: 'indoor-greenery',
    price: 4500,
    image: 'assets/images/pool/indoor-greenery-01.jpg',
    alt: 'A nursery-grown Swiss cheese plant, about 28 in tall, in a grow pot.',
    summary: 'A nursery-grown Swiss cheese plant, about 28 in tall, in a grow pot.',
    description: 'Grown on until the leaves have begun to split, and happy in bright indirect light. Forgiving if you forget it for a week.',
    specs: [['Height', 'Approx. 28 in incl. pot'], ['Pot', '7 in grow pot'], ['Light', 'Bright, indirect'], ['Water', 'When top 1 in dry'], ['Pet safe', 'No — toxic if eaten']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'heartleaf-philodendron',
    name: 'Heartleaf Philodendron',
    category: 'indoor-greenery',
    price: 3200,
    image: 'assets/images/pool/indoor-greenery-02.jpg',
    alt: 'An easygoing trailing philodendron for a shelf or hanging spot.',
    summary: 'An easygoing trailing philodendron for a shelf or hanging spot.',
    description: 'A lush trailing philodendron with glossy heart-shaped leaves that tolerates lower light and the odd missed watering. One of the easiest plants to keep alive.',
    specs: [['Length', 'Trails to 18 in'], ['Pot', '6 in grow pot'], ['Light', 'Low to bright indirect'], ['Water', 'When top 1 in dry'], ['Pet safe', 'No — toxic if eaten']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'swiss-cheese-vine-adansonii',
    name: 'Swiss Cheese Vine (Adansonii)',
    category: 'indoor-greenery',
    price: 3800,
    image: 'assets/images/pool/indoor-greenery-03.jpg',
    alt: 'A trailing monstera adansonii with delicately holed leaves.',
    summary: 'A trailing monstera adansonii with delicately holed leaves.',
    description: 'The lacier cousin of the classic monstera, with leaves full of neat holes. Trails beautifully from a shelf or climbs a small trellis.',
    specs: [['Length', 'Trails to 20 in'], ['Pot', '6 in grow pot'], ['Light', 'Bright, indirect'], ['Water', 'When top 1 in dry'], ['Pet safe', 'No — toxic if eaten']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'monstera-deliciosa-potted',
    name: 'Monstera Deliciosa, Potted',
    category: 'indoor-greenery',
    price: 5200,
    image: 'assets/images/pool/indoor-greenery-04.jpg',
    alt: 'A well-rooted monstera supplied in a simple terracotta pot.',
    summary: 'A well-rooted monstera supplied in a simple terracotta pot.',
    description: 'A healthy young monstera already potted into terracotta, so it is ready to place with no repotting. Bright indirect light and the occasional wipe of the leaves keep it glossy.',
    specs: [['Height', 'Approx. 24 in incl. pot'], ['Pot', 'Terracotta, 7 in'], ['Light', 'Bright, indirect'], ['Water', 'When top 1 in dry'], ['Pet safe', 'No — toxic if eaten']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'monstera-deliciosa-petite',
    name: 'Monstera Deliciosa \'Petite\'',
    category: 'indoor-greenery',
    price: 3600,
    image: 'assets/images/pool/indoor-greenery-05.jpg',
    alt: 'A compact monstera for a desk or narrow sill.',
    summary: 'A compact monstera for a desk or narrow sill.',
    description: 'A smaller-growing monstera that stays tidy, ideal where a full-size plant would crowd. Same handsome split leaves at a friendlier scale.',
    specs: [['Height', 'Approx. 16 in incl. pot'], ['Pot', '5 in grow pot'], ['Light', 'Bright, indirect'], ['Water', 'When top 1 in dry'], ['Pet safe', 'No — toxic if eaten']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'swiss-cheese-plant-ceramic',
    name: 'Swiss Cheese Plant, Ceramic',
    category: 'indoor-greenery',
    price: 4800,
    image: 'assets/images/pool/indoor-greenery-06.jpg',
    alt: 'An adansonii monstera supplied in a patterned ceramic cachepot.',
    summary: 'An adansonii monstera supplied in a patterned ceramic cachepot.',
    description: 'A bushy Swiss cheese plant already dropped into a decorative ceramic pot, ready to place on a sill. Turn it weekly so it grows evenly.',
    specs: [['Height', 'Approx. 18 in incl. pot'], ['Pot', 'Ceramic cachepot'], ['Light', 'Bright, indirect'], ['Water', 'When top 1 in dry'], ['Pet safe', 'No — toxic if eaten']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'monstera-deliciosa-mature',
    name: 'Monstera Deliciosa, Mature',
    category: 'indoor-greenery',
    price: 6800,
    image: 'assets/images/pool/indoor-greenery-07.jpg',
    alt: 'A fuller monstera with several large, deeply cut leaves.',
    summary: 'A fuller monstera with several large, deeply cut leaves.',
    description: 'A more established plant with big, dramatically fenestrated leaves for people who want impact now rather than in a year. Bright indirect light suits it best.',
    specs: [['Height', 'Approx. 32 in incl. pot'], ['Pot', '8 in grow pot'], ['Light', 'Bright, indirect'], ['Water', 'When top 2 in dry'], ['Pet safe', 'No — toxic if eaten']],
    stock: 'low-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'monstera-in-blush-pot',
    name: 'Monstera in Blush Pot',
    category: 'indoor-greenery',
    price: 5400,
    image: 'assets/images/pool/indoor-greenery-08.jpg',
    alt: 'A monstera styled in a warm blush ceramic pot.',
    summary: 'A monstera styled in a warm blush ceramic pot.',
    description: 'A healthy monstera paired with a soft blush cachepot — a ready-made gift or a quick way to warm up a shelf. No repotting needed.',
    specs: [['Height', 'Approx. 22 in incl. pot'], ['Pot', 'Blush ceramic'], ['Light', 'Bright, indirect'], ['Water', 'When top 1 in dry'], ['Pet safe', 'No — toxic if eaten']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'mini-monstera',
    name: 'Mini Monstera',
    category: 'indoor-greenery',
    price: 2800,
    image: 'assets/images/pool/indoor-greenery-09.jpg',
    alt: 'A small starter monstera for a windowsill or first plant.',
    summary: 'A small starter monstera for a windowsill or first plant.',
    description: 'A young monstera in a simple pot — an affordable way to start, and it grows fast in a bright spot. A good gift for a new plant parent.',
    specs: [['Height', 'Approx. 12 in incl. pot'], ['Pot', '4 in grow pot'], ['Light', 'Bright, indirect'], ['Water', 'When top 1 in dry'], ['Pet safe', 'No — toxic if eaten']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'monstera-deliciosa-young',
    name: 'Monstera Deliciosa, Young',
    category: 'indoor-greenery',
    price: 3000,
    image: 'assets/images/pool/indoor-greenery-10.jpg',
    alt: 'A single-stemmed young monstera ready to grow on.',
    summary: 'A single-stemmed young monstera ready to grow on.',
    description: 'A tidy young monstera with its first split leaf, in a plain white pot. Give it light and a season and it fills out fast.',
    specs: [['Height', 'Approx. 14 in incl. pot'], ['Pot', 'White, 5 in'], ['Light', 'Bright, indirect'], ['Water', 'When top 1 in dry'], ['Pet safe', 'No — toxic if eaten']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'portrait-face-planter-planted',
    name: 'Portrait Face Planter, Planted',
    category: 'indoor-greenery',
    price: 4200,
    image: 'assets/images/pool/indoor-greenery-11.jpg',
    alt: 'A quirky face planter arriving planted up with mixed greenery.',
    summary: 'A quirky face planter arriving planted up with mixed greenery.',
    description: 'A hand-painted portrait planter that arrives already planted with a mix of easy trailing greenery. Equal parts plant and conversation piece.',
    specs: [['Height', 'Approx. 10 in incl. pot'], ['Pot', 'Ceramic face planter'], ['Light', 'Bright, indirect'], ['Water', 'When top 1 in dry'], ['Pet safe', 'Mixed planting — keep from pets']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'monstera-styled-pot',
    name: 'Monstera, Styled Pot',
    category: 'indoor-greenery',
    price: 5600,
    image: 'assets/images/pool/indoor-greenery-12.jpg',
    alt: 'A monstera supplied in a neutral stoneware pot, styled to place.',
    summary: 'A monstera supplied in a neutral stoneware pot, styled to place.',
    description: 'A healthy monstera dropped into a neutral stoneware cachepot that suits almost any room. Ready to set down and enjoy.',
    specs: [['Height', 'Approx. 24 in incl. pot'], ['Pot', 'Stoneware cachepot'], ['Light', 'Bright, indirect'], ['Water', 'When top 1 in dry'], ['Pet safe', 'No — toxic if eaten']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'dieffenbachia-camille',
    name: 'Dieffenbachia \'Camille\'',
    category: 'indoor-greenery',
    price: 3400,
    image: 'assets/images/pool/indoor-greenery-13.jpg',
    alt: 'A dumb cane with creamy variegated leaves for a bright room.',
    summary: 'A dumb cane with creamy variegated leaves for a bright room.',
    description: 'Bold paddle leaves splashed cream and green make dieffenbachia a fast, forgiving way to fill a corner. Keep it out of cold drafts.',
    specs: [['Height', 'Approx. 20 in incl. pot'], ['Pot', '6 in grow pot'], ['Light', 'Bright, indirect'], ['Water', 'When top 1 in dry'], ['Pet safe', 'No — toxic if eaten']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'snake-plant-laurentii',
    name: 'Snake Plant \'Laurentii\'',
    category: 'indoor-greenery',
    price: 3200,
    image: 'assets/images/pool/indoor-greenery-14.jpg',
    alt: 'The near-indestructible upright houseplant, in a white pot.',
    summary: 'The near-indestructible upright houseplant, in a white pot.',
    description: 'Sansevieria \'Laurentii\', with tall leaves edged in gold, is the plant to buy if others have not survived you. It tolerates low light and long gaps between watering.',
    specs: [['Height', 'Approx. 22 in incl. pot'], ['Pot', 'White, 7 in'], ['Light', 'Low to bright indirect'], ['Water', 'Every 3–4 weeks'], ['Pet safe', 'No — mildly toxic']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'snake-plant-zeylanica',
    name: 'Snake Plant \'Zeylanica\'',
    category: 'indoor-greenery',
    price: 3000,
    image: 'assets/images/pool/indoor-greenery-15.jpg',
    alt: 'A hardy banded snake plant for a low-light corner.',
    summary: 'A hardy banded snake plant for a low-light corner.',
    description: 'The classic green-banded sansevieria — architectural, upright and almost impossible to kill. Perfect for a hallway or bathroom with little light.',
    specs: [['Height', 'Approx. 20 in incl. pot'], ['Pot', '6 in grow pot'], ['Light', 'Low to bright indirect'], ['Water', 'Every 3–4 weeks'], ['Pet safe', 'No — mildly toxic']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'snake-plant-tall',
    name: 'Snake Plant, Tall',
    category: 'indoor-greenery',
    price: 4200,
    image: 'assets/images/pool/indoor-greenery-16.jpg',
    alt: 'A taller snake plant in a bright white pot for a floor spot.',
    summary: 'A taller snake plant in a bright white pot for a floor spot.',
    description: 'A generous, tall sansevieria that works as a low-effort floor plant beside a console or sofa. Set it and forget it.',
    specs: [['Height', 'Approx. 30 in incl. pot'], ['Pot', 'White, 8 in'], ['Light', 'Low to bright indirect'], ['Water', 'Every 3–4 weeks'], ['Pet safe', 'No — mildly toxic']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'snake-plant-superba',
    name: 'Snake Plant \'Superba\'',
    category: 'indoor-greenery',
    price: 3400,
    image: 'assets/images/pool/indoor-greenery-17.jpg',
    alt: 'A compact, wide-leaved snake plant for a shelf.',
    summary: 'A compact, wide-leaved snake plant for a shelf.',
    description: 'A shorter, broad-leaved sansevieria with strong yellow margins, sized for a shelf or desk. As tough as its taller cousins.',
    specs: [['Height', 'Approx. 16 in incl. pot'], ['Pot', '6 in grow pot'], ['Light', 'Low to bright indirect'], ['Water', 'Every 3–4 weeks'], ['Pet safe', 'No — mildly toxic']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'snake-plant-terracotta',
    name: 'Snake Plant, Terracotta',
    category: 'indoor-greenery',
    price: 3600,
    image: 'assets/images/pool/indoor-greenery-18.jpg',
    alt: 'A snake plant supplied in a classic terracotta pot.',
    summary: 'A snake plant supplied in a classic terracotta pot.',
    description: 'A healthy sansevieria already potted in breathable terracotta, which suits its dislike of sitting wet. Ready to place, no repotting.',
    specs: [['Height', 'Approx. 20 in incl. pot'], ['Pot', 'Terracotta, 7 in'], ['Light', 'Low to bright indirect'], ['Water', 'Every 3–4 weeks'], ['Pet safe', 'No — mildly toxic']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'snake-plant-laurentii-large',
    name: 'Snake Plant \'Laurentii\', Large',
    category: 'indoor-greenery',
    price: 5200,
    image: 'assets/images/pool/indoor-greenery-19.jpg',
    alt: 'A big floor-standing snake plant for an easy green statement.',
    summary: 'A big floor-standing snake plant for an easy green statement.',
    description: 'A large, multi-stem \'Laurentii\' that fills a corner with upright, gold-edged blades. The lowest-maintenance floor plant we sell.',
    specs: [['Height', 'Approx. 34 in incl. pot'], ['Pot', '9 in grow pot'], ['Light', 'Low to bright indirect'], ['Water', 'Every 3–4 weeks'], ['Pet safe', 'No — mildly toxic']],
    stock: 'in-stock',
    bulky: true,
    featured: false
  },
  {
    id: 'snake-plant-floor',
    name: 'Snake Plant, Floor',
    category: 'indoor-greenery',
    price: 4800,
    image: 'assets/images/pool/indoor-greenery-20.jpg',
    alt: 'A tall, dense snake plant sized to stand on the floor.',
    summary: 'A tall, dense snake plant sized to stand on the floor.',
    description: 'A dense clump of tall sansevieria leaves that reads as a proper floor plant without the fuss. Thrives on neglect and a bright-ish corner.',
    specs: [['Height', 'Approx. 32 in incl. pot'], ['Pot', '8 in grow pot'], ['Light', 'Low to bright indirect'], ['Water', 'Every 3–4 weeks'], ['Pet safe', 'No — mildly toxic']],
    stock: 'in-stock',
    bulky: true,
    featured: false
  },
  {
    id: 'snake-plant-compact',
    name: 'Snake Plant, Compact',
    category: 'indoor-greenery',
    price: 2600,
    image: 'assets/images/pool/indoor-greenery-21.jpg',
    alt: 'A small snake plant in a carved gray pot for a mantel or sill.',
    summary: 'A small snake plant in a carved gray pot for a mantel or sill.',
    description: 'A neat, compact sansevieria in a carved gray pot — a low, tidy hit of green for a mantel or narrow sill. Almost impossible to kill.',
    specs: [['Height', 'Approx. 12 in incl. pot'], ['Pot', 'Carved gray, 5 in'], ['Light', 'Low to bright indirect'], ['Water', 'Every 3–4 weeks'], ['Pet safe', 'No — mildly toxic']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'garden-tool-wall-set',
    name: 'Garden Tool Wall Set',
    category: 'tools',
    price: 8900,
    image: 'assets/images/pool/tools-00.jpg',
    alt: 'A hanging set of long-handled garden tools with a wall rack.',
    summary: 'A hanging set of long-handled garden tools with a wall rack.',
    description: 'A coordinated set of long-handled tools — rake, hoe and cultivator — with a simple wall rack to keep them off the shed floor. Ash handles and coated steel heads.',
    specs: [['Contents', 'Rake, hoe, cultivator, rack'], ['Heads', 'Coated carbon steel'], ['Handles', 'Ash'], ['Warranty', '5 years']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'ashwood-hand-trowel',
    name: 'Ashwood Hand Trowel',
    category: 'tools',
    price: 2400,
    image: 'assets/images/pool/tools-01.jpg',
    alt: 'A forged hand trowel with a comfortable oiled ash handle.',
    summary: 'A forged hand trowel with a comfortable oiled ash handle.',
    description: 'A single-piece forged trowel that will not bend at the neck like pressed-steel ones, set into a smooth ash handle. The tool you reach for most.',
    specs: [['Head', 'Forged carbon steel'], ['Handle', 'Oiled ash'], ['Length', '13 in'], ['Warranty', '10 years']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'complete-tool-glove-kit',
    name: 'Complete Tool & Glove Kit',
    category: 'tools',
    price: 6400,
    image: 'assets/images/pool/tools-02.jpg',
    alt: 'A starter kit of hand tools and gloves on a tidy pegboard-ready rack.',
    summary: 'A starter kit of hand tools and gloves on a tidy pegboard-ready rack.',
    description: 'Everything a new gardener needs to begin — trowel, fork, weeder and a pair of gloves — chosen to actually last rather than to pad out a box.',
    specs: [['Contents', 'Trowel, fork, weeder, gloves'], ['Heads', 'Coated steel'], ['Handles', 'Softgrip'], ['Warranty', '3 years']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'harvest-snips',
    name: 'Harvest Snips',
    category: 'tools',
    price: 1600,
    image: 'assets/images/pool/tools-05.jpg',
    alt: 'Precise spring-loaded snips for herbs, flowers and light pruning.',
    summary: 'Precise spring-loaded snips for herbs, flowers and light pruning.',
    description: 'Lightweight stainless snips with a fine tip for cutting herbs, deadheading and taking cuttings. The spring returns them open so your hand does less work.',
    specs: [['Blades', 'Stainless steel'], ['Length', '7 in'], ['Feature', 'Spring-loaded'], ['Warranty', '5 years']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'hand-fork-trowel-set',
    name: 'Hand Fork & Trowel Set',
    category: 'tools',
    price: 3600,
    image: 'assets/images/pool/tools-06.jpg',
    alt: 'A matched forged fork and trowel with hardwood handles.',
    summary: 'A matched forged fork and trowel with hardwood handles.',
    description: 'A forged hand fork and trowel that share a clean, classic look and enough strength for stony soil. Ash handles with a leather hanging loop.',
    specs: [['Heads', 'Forged carbon steel'], ['Handles', 'Ash, leather loops'], ['Pieces', 'Fork and trowel'], ['Warranty', '10 years']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'galvanized-watering-can',
    name: 'Galvanized Watering Can',
    category: 'tools',
    price: 3800,
    image: 'assets/images/pool/tools-07.jpg',
    alt: 'A 1.5-gallon galvanized steel watering can with a brass rose.',
    summary: 'A 1.5-gallon galvanized steel watering can with a brass rose.',
    description: 'A proper galvanized can with a long spout for reaching to the back of a border and a removable brass rose for a soft shower. Ages to a handsome patina.',
    specs: [['Capacity', '1.5 gallons'], ['Material', 'Galvanized steel'], ['Rose', 'Removable brass'], ['Warranty', '2 years']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'bypass-pruning-shears',
    name: 'Bypass Pruning Shears',
    category: 'tools',
    price: 4200,
    image: 'assets/images/pool/tools-16.jpg',
    alt: 'Drop-forged bypass shears that leave a clean cut on living stems.',
    summary: 'Drop-forged bypass shears that leave a clean cut on living stems.',
    description: 'Bypass blades slice like scissors and leave a clean wound, unlike anvil pruners that crush. The blade is replaceable and sharpenable, with a sap groove to stop it gumming up.',
    specs: [['Cut capacity', 'Up to 3/4 in'], ['Blade', 'Replaceable, sharpenable'], ['Length', '8 in'], ['Warranty', '10 years']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'vintage-metal-watering-can',
    name: 'Vintage Metal Watering Can',
    category: 'tools',
    price: 3200,
    image: 'assets/images/pool/tools-30.jpg',
    alt: 'A slim pressed-metal watering can that doubles as a vase.',
    summary: 'A slim pressed-metal watering can that doubles as a vase.',
    description: 'A tall, characterful metal can with embossed measures — as at home holding a bunch of stems on the table as watering the sill. Indoor size.',
    specs: [['Capacity', '1 gallon'], ['Material', 'Pressed steel'], ['Use', 'Indoor watering, display'], ['Warranty', '2 years']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'steel-garden-wheelbarrow',
    name: 'Steel Garden Wheelbarrow',
    category: 'tools',
    price: 9600,
    image: 'assets/images/pool/tools-31.jpg',
    alt: 'A 6-cubic-foot steel wheelbarrow on a pneumatic tire, rated to 265 lb.',
    summary: 'A 6-cubic-foot steel wheelbarrow on a pneumatic tire, rated to 265 lb.',
    description: 'A single-wheel barrow with a galvanized tray that will not rust through at the seams, on a pneumatic tire that rolls over rough ground far better than solid wheels. Sleeved handles for cold mornings.',
    specs: [['Capacity', '6 cu ft'], ['Load rating', '265 lb'], ['Tray', 'Galvanized steel'], ['Tire', 'Pneumatic'], ['Warranty', '2 years']],
    stock: 'in-stock',
    bulky: true,
    featured: false
  },
  {
    id: '50-ft-garden-hose',
    name: '50 ft Garden Hose',
    category: 'tools',
    price: 4400,
    image: 'assets/images/pool/tools-32.jpg',
    alt: 'A kink-resistant 50-foot garden hose with brass fittings.',
    summary: 'A kink-resistant 50-foot garden hose with brass fittings.',
    description: 'A flexible, kink-resistant hose with solid brass couplings that seal without cross-threading. Long enough for most yards without dragging half the reel behind you.',
    specs: [['Length', '50 ft'], ['Fittings', 'Solid brass'], ['Feature', 'Kink-resistant'], ['Warranty', '5 years']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'leather-gardening-gloves',
    name: 'Leather Gardening Gloves',
    category: 'tools',
    price: 2800,
    image: 'assets/images/pool/tools-35.jpg',
    alt: 'Supple leather gloves that handle thorns and rough work.',
    summary: 'Supple leather gloves that handle thorns and rough work.',
    description: 'Full-grain leather gloves that protect against thorns and splinters while staying flexible enough for fiddly jobs. They soften and mold to your hands with use.',
    specs: [['Material', 'Full-grain leather'], ['Sizes', 'S–L'], ['Use', 'Pruning, heavy handling'], ['Warranty', '1 year']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'coated-grip-gloves',
    name: 'Coated Grip Gloves',
    category: 'tools',
    price: 1400,
    image: 'assets/images/pool/tools-36.jpg',
    alt: 'Breathable coated-palm gloves for everyday planting and weeding.',
    summary: 'Breathable coated-palm gloves for everyday planting and weeding.',
    description: 'Lightweight knit gloves with a coated palm for grip in damp soil — the pair you actually keep by the back door. Machine washable.',
    specs: [['Material', 'Knit, coated palm'], ['Sizes', 'S–L'], ['Care', 'Machine washable'], ['Warranty', '1 year']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'hori-hori-garden-knife',
    name: 'Hori-Hori Garden Knife',
    category: 'tools',
    price: 3400,
    image: 'assets/images/pool/tools-37.jpg',
    alt: 'A Japanese hori-hori knife for planting, dividing and weeding.',
    summary: 'A Japanese hori-hori knife for planting, dividing and weeding.',
    description: 'A heavy stainless blade with a serrated edge and depth markings that does the work of a trowel, saw and weeder at once. The one tool experienced gardeners never put down.',
    specs: [['Blade', 'Stainless steel, serrated edge'], ['Handle', 'Hardwood'], ['Sheath', 'Included'], ['Warranty', '10 years']],
    stock: 'low-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'garden-multi-tool-set',
    name: 'Garden Multi-Tool Set',
    category: 'tools',
    price: 4600,
    image: 'assets/images/pool/tools-38.jpg',
    alt: 'A flat-lay set of essential cutting and splitting tools for heavier jobs.',
    summary: 'A flat-lay set of essential cutting and splitting tools for heavier jobs.',
    description: 'A compact set for the jobs a trowel cannot do — a hand hatchet, folding saw and heavy knife for roots, kindling and clearing. Forged steel with hardwood handles.',
    specs: [['Contents', 'Hatchet, folding saw, knife'], ['Material', 'Forged steel, hardwood'], ['Storage', 'Roll included'], ['Warranty', '5 years']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'candle-lantern',
    name: 'Candle Lantern',
    category: 'lighting',
    price: 2400,
    image: 'assets/images/pool/lighting-00.jpg',
    alt: 'A simple black metal-and-glass lantern for a pillar candle.',
    summary: 'A simple black metal-and-glass lantern for a pillar candle.',
    description: 'A classic glass-paned lantern that shelters a candle from the breeze on a table or step. Warm, wire-free light for an evening outside.',
    specs: [['Material', 'Powder-coated steel, glass'], ['Fits', 'Pillar candle up to 6 in'], ['Use', 'Candle (not included)'], ['Weather', 'Covered use']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'globe-pendant-lantern',
    name: 'Globe Pendant Lantern',
    category: 'lighting',
    price: 5800,
    image: 'assets/images/pool/lighting-03.jpg',
    alt: 'A hanging globe lantern with a warm-white LED and dusk sensor.',
    summary: 'A hanging globe lantern with a warm-white LED and dusk sensor.',
    description: 'A gilt-framed glass globe that hangs from a branch or hook and lights itself at dusk. Battery LED, so there is no wiring and nothing to plug in.',
    specs: [['Light', 'Warm-white LED'], ['Power', 'Rechargeable battery'], ['Feature', 'Dusk sensor'], ['Weather', 'IP44']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'weathered-coach-lantern',
    name: 'Weathered Coach Lantern',
    category: 'lighting',
    price: 3600,
    image: 'assets/images/pool/lighting-04.jpg',
    alt: 'A vintage-style coach lantern with a weathered finish.',
    summary: 'A vintage-style coach lantern with a weathered finish.',
    description: 'A characterful coach lantern with a deliberately weathered finish that suits an older house or a shady corner. Takes a candle or a battery pillar.',
    specs: [['Material', 'Weathered steel, glass'], ['Fits', 'Pillar candle or LED'], ['Use', 'Hang or stand'], ['Weather', 'Covered use']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'hanging-barn-lantern',
    name: 'Hanging Barn Lantern',
    category: 'lighting',
    price: 3200,
    image: 'assets/images/pool/lighting-07.jpg',
    alt: 'A glowing barn-style lantern to hang in a tree or on a hook.',
    summary: 'A glowing barn-style lantern to hang in a tree or on a hook.',
    description: 'A tapered barn lantern that throws a soft pool of warm light from a branch or pergola. Battery LED with a flickering candle mode.',
    specs: [['Light', 'Warm-white LED, flicker mode'], ['Power', 'Battery'], ['Feature', 'Hook and handle'], ['Weather', 'IP44']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'cathedral-hanging-lantern',
    name: 'Cathedral Hanging Lantern',
    category: 'lighting',
    price: 4200,
    image: 'assets/images/pool/lighting-08.jpg',
    alt: 'A tall, slim lantern with cathedral glass panes.',
    summary: 'A tall, slim lantern with cathedral glass panes.',
    description: 'An elegant, tall lantern with arched glazing that suits a covered porch or a sheltered tree. Warm LED on a timer, no wiring needed.',
    specs: [['Light', 'Warm-white LED'], ['Power', 'Battery, timer'], ['Use', 'Hang'], ['Weather', 'IP44']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'classic-coach-lantern',
    name: 'Classic Coach Lantern',
    category: 'lighting',
    price: 3400,
    image: 'assets/images/pool/lighting-11.jpg',
    alt: 'A traditional coach lantern for a wall bracket or hook.',
    summary: 'A traditional coach lantern for a wall bracket or hook.',
    description: 'A neat, traditional coach lantern that looks right by a door or on a bracket. Warm LED with a dusk-to-dawn sensor so it minds itself.',
    specs: [['Light', 'Warm-white LED'], ['Power', 'Battery'], ['Feature', 'Dusk sensor'], ['Weather', 'IP44']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'orchard-hanging-lantern',
    name: 'Orchard Hanging Lantern',
    category: 'lighting',
    price: 3000,
    image: 'assets/images/pool/lighting-13.jpg',
    alt: 'A softly glowing lantern to string through trees and shrubs.',
    summary: 'A softly glowing lantern to string through trees and shrubs.',
    description: 'A lightweight lantern made to hang in numbers through an orchard or border for a magical evening. Warm LED, weather-resistant, easy to move.',
    specs: [['Light', 'Warm-white LED'], ['Power', 'Battery'], ['Use', 'Hang in groups'], ['Weather', 'IP44']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'caf-string-lights-24-ft',
    name: 'Café String Lights, 24 ft',
    category: 'lighting',
    price: 3800,
    image: 'assets/images/pool/lighting-30.jpg',
    alt: 'Twenty-four feet of connectable café lights with shatterproof bulbs.',
    summary: 'Twenty-four feet of connectable café lights with shatterproof bulbs.',
    description: 'Rubber-jacketed cable with warm shatterproof bulbs at 18-inch spacing, rated for the weather so it can stay up all season. Connect several sets from one outlet.',
    specs: [['Length', '24 ft lit'], ['Bulbs', '16 shatterproof LED'], ['Connectable', 'Up to 3 sets'], ['Weather', 'IP65']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'starry-night-string-lights',
    name: 'Starry Night String Lights',
    category: 'lighting',
    price: 4200,
    image: 'assets/images/pool/lighting-31.jpg',
    alt: 'Delicate string lights that read like a scatter of stars overhead.',
    summary: 'Delicate string lights that read like a scatter of stars overhead.',
    description: 'Fine-gauge string lights with small warm bulbs that all but disappear by day and glow like stars at night. Ideal woven through a pergola.',
    specs: [['Length', '33 ft lit'], ['Bulbs', '50 warm LED'], ['Feature', 'Fine gauge'], ['Weather', 'IP44']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'edison-bulb-string-set',
    name: 'Edison Bulb String Set',
    category: 'lighting',
    price: 4600,
    image: 'assets/images/pool/lighting-32.jpg',
    alt: 'Vintage-look Edison bulbs on a heavy-duty weatherproof cable.',
    summary: 'Vintage-look Edison bulbs on a heavy-duty weatherproof cable.',
    description: 'Amber Edison-style LED bulbs on a rugged cable for a warm, characterful glow over a table or bar. The LEDs sip power but look like the real filament thing.',
    specs: [['Length', '24 ft lit'], ['Bulbs', '12 Edison-style LED'], ['Connectable', 'Up to 3 sets'], ['Weather', 'IP65']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'bistro-string-lights-48-ft',
    name: 'Bistro String Lights, 48 ft',
    category: 'lighting',
    price: 5400,
    image: 'assets/images/pool/lighting-33.jpg',
    alt: 'A long 48-foot run of bistro lights for larger yards and decks.',
    summary: 'A long 48-foot run of bistro lights for larger yards and decks.',
    description: 'A generous run of weatherproof bistro lights to cross a whole patio or wrap a large tree, with spare bulbs in the box. One plug does the lot.',
    specs: [['Length', '48 ft lit'], ['Bulbs', '30 shatterproof LED + spares'], ['Connectable', 'Yes'], ['Weather', 'IP65']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'solar-firefly-lights',
    name: 'Solar Firefly Lights',
    category: 'lighting',
    price: 2800,
    image: 'assets/images/pool/lighting-34.jpg',
    alt: 'Solar-powered firefly lights that flicker softly after dark.',
    summary: 'Solar-powered firefly lights that flicker softly after dark.',
    description: 'A cluster of tiny solar lights on flexible stems that twinkle among planting like fireflies. No wiring and no running cost — they charge by day and switch on at dusk.',
    specs: [['Light', 'Warm-white LED'], ['Power', 'Solar'], ['Feature', 'Dusk sensor'], ['Weather', 'IP44']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'weatherproof-string-lights',
    name: 'Weatherproof String Lights',
    category: 'lighting',
    price: 3600,
    image: 'assets/images/pool/lighting-35.jpg',
    alt: 'A rugged string set built to survive winters outdoors.',
    summary: 'A rugged string set built to survive winters outdoors.',
    description: 'Heavy-jacketed cable and sealed shatterproof bulbs designed to stay up year-round without a flicker. The set to buy if you hate taking lights down.',
    specs: [['Length', '32 ft lit'], ['Bulbs', '20 shatterproof LED'], ['Connectable', 'Yes'], ['Weather', 'IP65']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'commercial-grade-string-lights',
    name: 'Commercial-Grade String Lights',
    category: 'lighting',
    price: 6400,
    image: 'assets/images/pool/lighting-36.jpg',
    alt: 'Contractor-grade string lights for big spans and long life.',
    summary: 'Contractor-grade string lights for big spans and long life.',
    description: 'The string lights restaurants use — thick cable, replaceable bulbs and connectors rated for long outdoor runs. Overkill for a balcony, perfect for a big yard.',
    specs: [['Length', '54 ft lit'], ['Bulbs', '24 replaceable LED'], ['Connectable', 'End to end'], ['Weather', 'IP65']],
    stock: 'low-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'pendant-bulb-light',
    name: 'Pendant Bulb Light',
    category: 'lighting',
    price: 2200,
    image: 'assets/images/pool/lighting-37.jpg',
    alt: 'A single weatherproof pendant bulb for a focused pool of light.',
    summary: 'A single weatherproof pendant bulb for a focused pool of light.',
    description: 'One good-looking pendant bulb on a weatherproof lead — hang a few at different heights over a table for a relaxed, gallery-like effect. Warm dimmable LED.',
    specs: [['Light', 'Warm dimmable LED'], ['Lead', '6 ft'], ['Use', 'Single or grouped'], ['Weather', 'IP44']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'hanging-bulb-garland',
    name: 'Hanging Bulb Garland',
    category: 'lighting',
    price: 3000,
    image: 'assets/images/pool/lighting-38.jpg',
    alt: 'A short garland of warm bulbs to drape over a doorway or arch.',
    summary: 'A short garland of warm bulbs to drape over a doorway or arch.',
    description: 'A compact garland of warm bulbs sized to frame a doorway, window or garden arch. Plug-in, weather-resistant and endlessly re-drapeable.',
    specs: [['Length', '12 ft lit'], ['Bulbs', '10 warm LED'], ['Use', 'Doorways, arches'], ['Weather', 'IP44']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'elephant-garden-statue',
    name: 'Elephant Garden Statue',
    category: 'decor',
    price: 12900,
    image: 'assets/images/pool/decor-00.jpg',
    alt: 'A characterful cast-stone elephant to anchor a border or entrance.',
    summary: 'A characterful cast-stone elephant to anchor a border or entrance.',
    description: 'A weighty cast-stone elephant with lovely detail that becomes a focal point among planting or beside a door. Weathers naturally and mosses gently over the years.',
    specs: [['Material', 'Cast stone'], ['Size', 'H 18 in'], ['Weight', '31 lb'], ['Weather', 'Frost-proof']],
    stock: 'low-stock',
    bulky: true,
    featured: true
  },
  {
    id: 'hummingbird-solar-stake',
    name: 'Hummingbird Solar Stake',
    category: 'decor',
    price: 2400,
    image: 'assets/images/pool/decor-01.jpg',
    alt: 'A solar garden stake with a jewel-toned hummingbird that glows at night.',
    summary: 'A solar garden stake with a jewel-toned hummingbird that glows at night.',
    description: 'A decorative stake topped with a metal-and-glass hummingbird that charges by day and casts a soft colored glow at dusk. A little joy pushed into a border.',
    specs: [['Material', 'Metal, glass'], ['Height', '34 in stake'], ['Power', 'Solar'], ['Weather', 'Weather-resistant']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'cupped-hands-bird-bath',
    name: 'Cupped Hands Bird Bath',
    category: 'decor',
    price: 8900,
    image: 'assets/images/pool/decor-02.jpg',
    alt: 'A cast-stone bird bath shaped as a pair of cupped hands.',
    summary: 'A cast-stone bird bath shaped as a pair of cupped hands.',
    description: 'A gentle, sculptural bird bath in the form of cupped hands that draws birds to a quiet corner. Cast stone that weathers beautifully; empty before a hard freeze.',
    specs: [['Material', 'Cast stone'], ['Size', 'Ø 14 in bowl'], ['Weight', '22 lb'], ['Weather', 'Empty before freezing']],
    stock: 'in-stock',
    bulky: true,
    featured: true
  },
  {
    id: 'glass-globe-finial',
    name: 'Glass Globe Finial',
    category: 'decor',
    price: 3200,
    image: 'assets/images/pool/decor-03.jpg',
    alt: 'A blown-glass globe finial on a metal stand for a border accent.',
    summary: 'A blown-glass globe finial on a metal stand for a border accent.',
    description: 'A hand-blown glass globe on a slender stand that catches the light among planting like a soap bubble caught mid-air. A quiet, pretty full stop for a bed.',
    specs: [['Material', 'Blown glass, metal'], ['Height', '24 in'], ['Use', 'Border accent'], ['Weather', 'Bring in over winter']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'gargoyle-sentry-statue',
    name: 'Gargoyle Sentry Statue',
    category: 'decor',
    price: 6900,
    image: 'assets/images/pool/decor-04.jpg',
    alt: 'A brooding cast-stone gargoyle to stand guard by a step or gate.',
    summary: 'A brooding cast-stone gargoyle to stand guard by a step or gate.',
    description: 'A characterful crouching gargoyle in cast stone, all folded wings and gothic charm, to perch by a step or gatepost. Frost-proof and built to weather.',
    specs: [['Material', 'Cast stone'], ['Size', 'H 12 in'], ['Weight', '15 lb'], ['Weather', 'Frost-proof']],
    stock: 'in-stock',
    bulky: true,
    featured: false
  },
  {
    id: 'stone-owl-ornament',
    name: 'Stone Owl Ornament',
    category: 'decor',
    price: 4200,
    image: 'assets/images/pool/decor-05.jpg',
    alt: 'A serene cast-stone owl for a wall, post or shelf in the garden.',
    summary: 'A serene cast-stone owl for a wall, post or shelf in the garden.',
    description: 'A calm, well-observed owl in cast stone that looks at home on a wall top or among ferns. Weathers to a soft, lichened gray over time.',
    specs: [['Material', 'Cast stone'], ['Size', 'H 9 in'], ['Weight', '6 lb'], ['Weather', 'Frost-proof']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'reclining-cat-statue',
    name: 'Reclining Cat Statue',
    category: 'decor',
    price: 4600,
    image: 'assets/images/pool/decor-06.jpg',
    alt: 'A stone cat curled mid-stretch, for a border or doorstep.',
    summary: 'A stone cat curled mid-stretch, for a border or doorstep.',
    description: 'A relaxed reclining cat in cast stone, caught mid-stretch, that surprises visitors tucked among the planting. Frost-proof and full of character.',
    specs: [['Material', 'Cast stone'], ['Size', 'L 14 in'], ['Weight', '8 lb'], ['Weather', 'Frost-proof']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'stone-tortoise-ornament',
    name: 'Stone Tortoise Ornament',
    category: 'decor',
    price: 3800,
    image: 'assets/images/pool/decor-07.jpg',
    alt: 'A patient cast-stone tortoise to tuck among low planting.',
    summary: 'A patient cast-stone tortoise to tuck among low planting.',
    description: 'A finely shelled tortoise in cast stone that peers out from the front of a border or the edge of a path. A gentle bit of whimsy that lasts for years.',
    specs: [['Material', 'Cast stone'], ['Size', 'L 11 in'], ['Weight', '6 lb'], ['Weather', 'Frost-proof']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'gingham-outdoor-pillow',
    name: 'Gingham Outdoor Pillow',
    category: 'decor',
    price: 2400,
    image: 'assets/images/pool/decor-08.jpg',
    alt: 'A blue gingham outdoor throw pillow in fade-resistant fabric.',
    summary: 'A blue gingham outdoor throw pillow in fade-resistant fabric.',
    description: 'A cheerful blue gingham pillow in solution-dyed fabric that shrugs off sun and the odd shower. An easy way to freshen a bench or chair.',
    specs: [['Cover', 'Solution-dyed, fade-resistant'], ['Size', '18 in square'], ['Fill', 'Water-resistant, included'], ['Care', 'Wipe or machine wash cover']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'striped-bench-cushions-set-of-3',
    name: 'Striped Bench Cushions, Set of 3',
    category: 'decor',
    price: 4900,
    image: 'assets/images/pool/decor-10.jpg',
    alt: 'Three coordinating striped cushions to dress a bench or sofa.',
    summary: 'Three coordinating striped cushions to dress a bench or sofa.',
    description: 'A set of three woven-stripe cushions in mixed sizes that instantly soften a bench or outdoor sofa. Covers unzip for washing; pads included.',
    specs: [['Cover', 'Woven, fade-resistant'], ['Sizes', '3 mixed'], ['Fill', 'Recycled pads, included'], ['Care', 'Machine wash covers']],
    stock: 'in-stock',
    bulky: false,
    featured: true
  },
  {
    id: 'embroidered-seat-cushion',
    name: 'Embroidered Seat Cushion',
    category: 'decor',
    price: 2900,
    image: 'assets/images/pool/decor-13.jpg',
    alt: 'A hand-embroidered seat cushion with ties for a dining chair.',
    summary: 'A hand-embroidered seat cushion with ties for a dining chair.',
    description: 'A tailored seat cushion with a delicate embroidered motif and ties to keep it put. Adds comfort and a little detail to a hard chair.',
    specs: [['Cover', 'Cotton, embroidered'], ['Size', '16 in square'], ['Fill', 'Included, washable cover'], ['Care', 'Machine wash cover']],
    stock: 'in-stock',
    bulky: false,
    featured: false
  },
  {
    id: 'braided-runner-rug',
    name: 'Braided Runner Rug',
    category: 'decor',
    price: 5900,
    image: 'assets/images/pool/decor-14.jpg',
    alt: 'A pink braided runner for a hallway, porch or garden room.',
    summary: 'A pink braided runner for a hallway, porch or garden room.',
    description: 'A flat-braided runner in soft pinks that brings warmth to a hallway or covered porch. Reversible and hard-wearing; best kept out of standing water.',
    specs: [['Material', 'Braided cotton'], ['Size', '24 × 72 in'], ['Feature', 'Reversible'], ['Care', 'Vacuum; spot clean']],
    stock: 'in-stock',
    bulky: true,
    featured: false
  },
  {
    id: 'round-chindi-rug',
    name: 'Round Chindi Rug',
    category: 'decor',
    price: 6900,
    image: 'assets/images/pool/decor-15.jpg',
    alt: 'A vibrant round braided chindi rug with a fringed edge.',
    summary: 'A vibrant round braided chindi rug with a fringed edge.',
    description: 'A joyful round rug hand-braided from recycled cotton in a riot of color, with a fringed edge. A quick way to define a seating spot indoors or on a covered deck.',
    specs: [['Material', 'Recycled cotton (chindi)'], ['Size', 'Ø 48 in'], ['Feature', 'Reversible, fringed'], ['Care', 'Vacuum; spot clean']],
    stock: 'in-stock',
    bulky: true,
    featured: true
  },
  {
    id: 'natural-jute-rug',
    name: 'Natural Jute Rug',
    category: 'decor',
    price: 11900,
    image: 'assets/images/pool/decor-16.jpg',
    alt: 'A hand-woven jute rug in undyed natural fiber.',
    summary: 'A hand-woven jute rug in undyed natural fiber.',
    description: 'A flat-woven jute rug in undyed fiber, so the color is the plant itself rather than a dye that fades. Hard-wearing and textural; keep it under cover, as jute dislikes standing water.',
    specs: [['Material', '100% undyed jute'], ['Size', '63 × 90 in'], ['Feature', 'Reversible'], ['Care', 'Vacuum; blot spills']],
    stock: 'in-stock',
    bulky: true,
    featured: true
  },
  {
    id: 'braided-cotton-area-rug',
    name: 'Braided Cotton Area Rug',
    category: 'decor',
    price: 8900,
    image: 'assets/images/pool/decor-17.jpg',
    alt: 'A rectangular braided rug with a colorful medallion border.',
    summary: 'A rectangular braided rug with a colorful medallion border.',
    description: 'A hard-wearing braided area rug with a lively medallion border that hides everyday wear. Reversible for twice the life; ideal for a garden room or porch.',
    specs: [['Material', 'Braided cotton'], ['Size', '48 × 72 in'], ['Feature', 'Reversible'], ['Care', 'Vacuum; spot clean']],
    stock: 'in-stock',
    bulky: true,
    featured: false
  }
];

/** Human-readable stock states. Only states the shop could genuinely assert. */
export const STOCK_LABELS = {
  'in-stock': { text: 'In stock', tone: 'good' },
  'low-stock': { text: 'Low stock', tone: 'warn' },
  'out-of-stock': { text: 'Out of stock', tone: 'bad' }
};

export function findProduct(id) {
  return PRODUCTS.find((product) => product.id === id) || null;
}

export function findCategory(id) {
  return CATEGORIES.find((category) => category.id === id) || null;
}

/** Format an integer number of cents as a US dollar price string. */
export function formatPrice(cents) {
  return '$' + (cents / 100).toFixed(2);
}
